### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by FGRibreau** [evilbluebeaver/zset#1]
Nice implementation @evilbluebeaver,!

Even if it's not related to Redis directly, your zset implementation in erlang will be shared in our next [RedisWeekly](http://redisweekly.com/)! Once published (in a matter of minutes) you will be able to see your [projet description here](http://redisweekly.com/archive/139.html) :)

**Comment by evilbluebeaver** [comment]
Thank you @FGRibreau. I'm glad you liked my library. Any suggestions for improvement are welcome.
